"""
Django settings for mypython project.

Generated by 'django-admin startproject' using Django 2.0.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__))) #项目的根目录


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = ')yico5&&nvzimav8+ce0a-pn-$6y^y92=do*h^-fsxxmn5c^=$'  #项目安全码 启动项目 必须要有 一般不需要管

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True    #是否开启调试模式

ALLOWED_HOSTS = [] #允许访问我们网站的地址列表 只有使用添加在这个列表里的地址访问我们的网站才能访问到。


# Application definition

INSTALLED_APPS = [                   #已安装的应用 每次创建我们自己的应用 需要把应用写在这里。
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'blog',
]

MIDDLEWARE = [                       # 中间件
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mypython.urls'       #URL根配置文件

TEMPLATES = [                        #模板文件
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mypython.wsgi.application'     # -----


# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {                          #数据库配置
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'pythonpractice',
        'USER': 'postgres',
        'PASSWORD': '123456',
        'HOST': '127.0.0.1',
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [     #密码认证项目
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'zh_Hans'     #网站的使用语言

TIME_ZONE = 'UTC'             #时区

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/


SITE_ROOT=os.path.join(os.path.abspath(os.path.dirname(__file__)),'..')
static = os.path.join(SITE_ROOT,'static')
# STATIC_ROOT = os.path.abspath(STATIC_ROOT)
STATIC_URL = '/static/'          #静态文件地址配置 这个配置主要是给templates用到 正常的页面请求静态文件跟这个参数无关。
STATICFILES_DIRS = [
    os.path.abspath(static)
]